version: "3.8"
services:
  grok2api_python:
    build:
      context: . # 你的代码所在目录（含 app.py / requirements.txt / Dockerfile）
      dockerfile: Dockerfile
    image: grok2api_python:local
    container_name: grok2api_python_local
    ports:
      - "3000:3000"
    environment:
      - IS_TEMP_CONVERSATION=true
      - IS_CUSTOM_SSO=false
      - ISSHOW_SEARCH_RESULTS=false
      - PORT=3000
      - SHOW_THINKING=true
      - SSO_SUPER=ssoCookie1;ssoCookie2;ssoCookie3
    restart: unless-stopped
