version: "3.8"
services:
  grok2api_python:
    build:
      context: . # 你的代码所在目录（含 app.py / requirements.txt / Dockerfile）
      dockerfile: Dockerfile
    image: grok2api_python:local
    container_name: grok2api_python_local
    ports:
      - "3000:3000"
    environment:
      - IS_TEMP_CONVERSATION=true
      - IS_CUSTOM_SSO=false
      - ISSHOW_SEARCH_RESULTS=false
      - PORT=3000
      - SHOW_THINKING=true
      - SSO_SUPER=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzZXNzaW9uX2lkIjoiM2M1ZjU5YzgtNzE5Yi00YzIwLWFmNmItYzkyOGI5NDJhOTJlIn0.KT3tYX3Qb7_X6SIMnsidbuh6HE-J5XF6Ge17YUi-n1w
    restart: unless-stopped
